import type { CategoryTile, Product, Review } from "./types";

export const SITE = {
  name: "Chocova Valencia",
  tagline: "Pastelería artesanal y tartas personalizadas",
  address: "Carrer de Matias Perelló, 55, 46005 Valencia, España",
  phone: "962 066 840",
  whatsapp: "34607232316",
  whatsappDisplay: "607 232 316",
  email: "info@chocovavalencia.com",
  instagram: "https://www.instagram.com/chocovavalencia/",
  rating: 4.8,
  reviewCount: 168,
  hours: "Abierto · Cerramos a las 19:30",
};

export const NAV_LINKS = [
  { href: "/boutique", label: "Tienda" },
  { href: "/gateaux-sur-mesure", label: "Personalizadas" },
  { href: "/mariage", label: "Celebraciones" },
  { href: "/notre-histoire", label: "Nuestra historia" },
  { href: "/contact", label: "Contacto" },
];

export const CATEGORY_TILES: CategoryTile[] = [
  {
    id: "patisseries",
    title: "Tartas de la semana",
    description: "Tartas refrigeradas que cambian cada semana",
    href: "/boutique/patisseries",
    image: "/chocova/tarta-semanal.jpg",
  },
  {
    id: "gateaux",
    title: "Tartas",
    description: "Cumpleaños, fiestas y grandes celebraciones",
    href: "/boutique/gateaux",
    image: "/chocova/tarta-adultos.jpg",
  },
  {
    id: "custom",
    title: "Eventos",
    description: "Mesas dulces y tartas para cada celebración",
    href: "/gateaux-sur-mesure",
    image: "/chocova/tarta-impresion.jpg",
  },
  {
    id: "celebrations",
    title: "Celebraciones",
    description: "Tartas para los momentos más especiales",
    href: "/mariage",
    image: "/chocova/comunion.jpg",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "tartas-personalizadas",
    name: "Tartas Personalizadas",
    description: "Una tarta creada contigo para reflejar tu historia, tema y estilo.",
    category: "tartas-personalizadas",
    image: "/chocova/martina.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
    featured: true,
  },
  {
    id: "tartas-impresion",
    name: "Tartas de Impresión",
    description: "Diseño comestible impreso para personalizar el acabado de tu tarta.",
    category: "tartas-impresion",
    image: "/chocova/tarta-impresion.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
    featured: true,
  },
  {
    id: "tartas-numero",
    name: "Tartas Número",
    description: "Una tarta con el número protagonista de tu celebración.",
    category: "tartas-numero",
    image: "/chocova/tarta-numeros.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
    featured: true,
  },
  {
    id: "tartas-nevera",
    name: "Tartas de la semana",
    description: "Tartas refrigeradas que cambian cada semana.",
    category: "tartas-nevera",
    image: "/chocova/tarta-semanal.jpg",
    cta: "quote",
    availability: "Consultar disponibilidad",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-semanal-chocolate",
    name: "Tarta de chocolate",
    description: "Una tarta de chocolate para disfrutar durante la semana.",
    category: "tartas-nevera",
    image: "/portfolio/adultos/01.jpg",
    cta: "quote",
    availability: "Consultar disponibilidad",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-semanal-frutas",
    name: "Tarta de frutas",
    description: "Una creación fresca y delicada para compartir.",
    category: "tartas-nevera",
    image: "/portfolio/adultos/02.jpg",
    cta: "quote",
    availability: "Consultar disponibilidad",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-semanal-flores",
    name: "Tarta floral",
    description: "Una propuesta artesanal con una decoración cuidada.",
    category: "tartas-nevera",
    image: "/portfolio/adultos/03.jpg",
    cta: "quote",
    availability: "Consultar disponibilidad",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-semanal-celebracion",
    name: "Tarta de celebración",
    description: "Un dulce especial para celebrar cualquier momento.",
    category: "tartas-nevera",
    image: "/portfolio/adultos/04.jpg",
    cta: "quote",
    availability: "Consultar disponibilidad",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-infantil-personalizada",
    name: "Tarta infantil personalizada",
    description: "Una creación a medida para una celebración infantil.",
    category: "tartas-personalizadas",
    image: "/portfolio/infantiles/01.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-adultos-personalizada",
    name: "Tarta para adultos",
    description: "Una tarta personalizada para cumpleaños y momentos especiales.",
    category: "tartas-personalizadas",
    image: "/portfolio/adultos/05.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-numero-personalizada",
    name: "Tarta número personalizada",
    description: "Un diseño dulce con el número protagonista de tu celebración.",
    category: "tartas-numero",
    image: "/portfolio/infantiles/02.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "mesa-dulce-personalizada",
    name: "Mesa dulce personalizada",
    description: "Una selección de dulces creada para tu evento.",
    category: "mesas-dulces",
    image: "/portfolio/mesas-dulces/02.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-bautizo-personalizada",
    name: "Tarta de bautizo personalizada",
    description: "Una creación delicada para celebrar en familia.",
    category: "bautizos",
    image: "/portfolio/bautizos-comuniones/02.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-comunion-personalizada",
    name: "Tarta de comunión personalizada",
    description: "Un diseño especial para un día inolvidable.",
    category: "comuniones",
    image: "/portfolio/bautizos-comuniones/03.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-boda-personalizada",
    name: "Tarta de boda personalizada",
    description: "Una tarta artesanal para acompañar vuestro gran día.",
    category: "bodas",
    image: "/portfolio/bodas/02.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "tarta-empresa-personalizada",
    name: "Tarta para empresas",
    description: "Una propuesta dulce a medida para marcas y equipos.",
    category: "eventos-corporativos",
    image: "/portfolio/empresas/01.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },  {
    id: "donuts-rellenos",
    name: "Donuts Rellenos",
    description: "Donuts preparados para rellenar y decorar al gusto.",
    category: "donuts-rellenos",
    image: "/chocova/donuts.jpg",
    cta: "cart",
    availability: "Consultar disponibilidad",
    featured: true,
  },
  {
    id: "brownies",
    name: "Brownies",
    description: "Porciones de brownie para disfrutar o compartir.",
    category: "brownies",
    image: "/chocova/brownies.jpg",
    cta: "cart",
    availability: "Consultar disponibilidad",
  },
  {
    id: "muffins",
    name: "Muffins",
    description: "Muffins tiernos para desayunos, meriendas y mesas dulces.",
    category: "muffins",
    image: "/chocova/muffins.jpg",
    cta: "cart",
    availability: "Consultar disponibilidad",
  },
  {
    id: "cupcakes",
    name: "Cupcakes",
    description: "Cupcakes decorados para disfrutar en cualquier ocasión.",
    category: "cupcakes",
    image: "/chocova/cupcakes.jpeg",
    cta: "cart",
    availability: "Consultar disponibilidad",
  },
  {
    id: "cookies",
    name: "Cookies",
    description: "Cookies artesanales para acompañar tus momentos más dulces.",
    category: "cookies",
    image: "/chocova/cookies.jpeg",
    cta: "cart",
    availability: "Consultar disponibilidad",
  },
  {
    id: "mesas-dulces",
    name: "Mesas Dulces",
    description: "Una composición dulce completa para vestir tu celebración.",
    category: "mesas-dulces",
    image: "/chocova/mesas-dulces.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
    featured: true,
  },
  {
    id: "cumpleanos",
    name: "Cumpleaños",
    description: "Una tarta pensada para hacer inolvidable tu celebración.",
    category: "cumpleanos",
    image: "https://chocovavalencia.com/wp-content/uploads/2020/12/martina.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "bautizos",
    name: "Bautizos",
    description: "Diseños delicados para acompañar un día especial en familia.",
    category: "bautizos",
    image: "/chocova/bautizo.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "comuniones",
    name: "Comuniones",
    description: "Creaciones cuidadas para celebrar y compartir en familia.",
    category: "comuniones",
    image: "/chocova/comunion.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "bodas",
    name: "Bodas",
    description: "Tartas nupciales personalizadas para vuestro gran día.",
    category: "bodas",
    image: "/chocova/boda.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
  {
    id: "eventos-corporativos",
    name: "Eventos Corporativos",
    description: "Propuestas dulces a medida para eventos y equipos.",
    category: "eventos-corporativos",
    image: "/chocova/tartas-empresa.jpg",
    cta: "quote",
    availability: "Encargar con antelación",
    priceLabel: "Precio según diseño",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "1",
    author: "Maria K.",
    rating: 5,
    text: "¡Delicioso! Gran variedad de postres de todo el mundo. Sus tartas de cumpleaños infantiles siempre están riquísimas y la decoración es preciosa.",
    tag: "Cumpleaños",
  },
  {
    id: "2",
    author: "Victorine D.",
    rating: 5,
    text: "Llevo más de 5 años encargando mis tartas y nunca me han decepcionado. Un trato muy profesional y cercano. ¡Estoy deseando ver mi tarta nupcial!",
    tag: "Bodas",
  },
  {
    id: "3",
    author: "Sonia R.",
    rating: 5,
    text: "Excelente selección de dulces y propuestas saladas. El khachapuri estaba increíble: crujiente y fundente por dentro.",
    tag: "Pastelería",
  },
  {
    id: "4",
    author: "Cliente de Google",
    rating: 5,
    text: "Atención cercana, dulces deliciosos y tartas preciosas. Una visita imprescindible en Valencia.",
    tag: "Atención",
  },
  {
    id: "5",
    author: "Sophie L.",
    rating: 5,
    text: "La tarta de fresas es una maravilla. Se nota el trabajo artesanal en cada bocado.",
    tag: "Pastelería",
  },
];

export const INSTAGRAM_POSTS = [
  {
    id: "1",
    image:
      "/instagram/506395092_1243760020456100_8896445037206883256_n.jpg",
    alt: "Tarta de chocolate",
  },
  {
    id: "2",
    image:
      "/instagram/510957703_18083241469752445_4666203883791157357_n.jpg",
    alt: "Tarta de fresas",
  },
  {
    id: "3",
    image:
      "/instagram/581740305_18096868219752445_6650576276840332859_n.jpg",
    alt: "Tarta nupcial",
  },
  {
    id: "4",
    image:
      "/instagram/610308441_18102543748752445_3962388717944611297_n.jpg",
    alt: "Bollería",
  },
  {
    id: "5",
    image:
      "/instagram/611665104_18102543685752445_5628411739489225522_n.jpg",
    alt: "Tarta personalizada",
  },
  {
    id: "6",
    image:
      "/instagram/620982637_18104295232752445_3470182747740634475_n.jpg",
    alt: "Creación dulce de Chocova Valencia",
  },
  {
    id: "7",
    image: "/instagram/624160035_18105362659752445_7922337456158117569_n.jpg",
    alt: "Tarta ecuestre personalizada",
  },
  {
    id: "8",
    image: "/instagram/722637648_18118421716752445_430082563389280011_n.jpg",
    alt: "Tarta de bautizo azul cielo",
  },
  {
    id: "9",
    image: "/instagram/731142429_18120781585752445_2027953214602976917_n.jpg",
    alt: "Tarta de dieciocho años con temática oceánica",
  },
  {
    id: "10",
    image: "/instagram/731175343_18120781567752445_7006623568685025379_n.jpg",
    alt: "Tarta naranja Aperol Spritz",
  },
];

export function getProductsByCategory(category: Product["category"]) {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByCategories(categories: Product["category"][]) {
  return PRODUCTS.filter((p) => categories.includes(p.category));
}

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.featured);
}
